**Assignment-16**

Recommendation System

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('/content/anime.csv')

In [7]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [8]:
df.shape

(12294, 7)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [10]:
df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [11]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

anime_id      int64
name         object
genre        object
type         object
episodes     object
rating      float64
members       int64
dtype: object

In [14]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [15]:
features = ['genre','rating']

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit_transform(df['genre'])
df['genre'] = le.fit_transform(df['genre'])

In [17]:
features

['genre', 'rating']

In [18]:
df[features].head()

   genre  rating
0   2686    9.37
1    161    9.26
2    534    9.25
3   3240    9.17
4    534    9.16

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()

In [21]:
X_scaled = scaler.fit_transform(df[features])

In [22]:
X_scaled[:5]

array([[ 0.78573595,  2.82077308],
       [-1.95016038,  2.7136341 ],
       [-1.54600619,  2.70389419],
       [ 1.38600786,  2.62597493],
       [-1.54600619,  2.61623502]])

In [23]:
X_scaled

array([[ 0.78573595,  2.82077308],
       [-1.95016038,  2.7136341 ],
       [-1.54600619,  2.70389419],
       ...,
       [ 1.0208605 , -1.55244557],
       [ 1.0208605 , -1.45504649],
       [ 1.0208605 , -0.98753091]])

In [28]:
import numpy as np

np.isnan(X_scaled).sum()

np.int64(230)

In [29]:
df[features].isnull().sum()

genre       0
rating    230
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [35]:
df['rating'].fillna(df['rating'].mean())

0        9.37
1        9.26
2        9.25
3        9.17
4        9.16
         ...
12289    4.15
12290    4.28
12291    4.88
12292    4.98
12293    5.46
Name: rating, Length: 12294, dtype: float64

In [36]:
df.rating

0        9.37
1        9.26
2        9.25
3        9.17
4        9.16
         ...
12289    4.15
12290    4.28
12291    4.88
12292    4.98
12293    5.46
Name: rating, Length: 12294, dtype: float64

In [37]:
df[features].isnull().sum()

genre     0
rating    0
dtype: int64

In [38]:
X_scaled

array([[ 0.78573595,  2.82077308],
       [-1.95016038,  2.7136341 ],
       [-1.54600619,  2.70389419],
       ...,
       [ 1.0208605 , -1.55244557],
       [ 1.0208605 , -1.45504649],
       [ 1.0208605 , -0.98753091]])

In [42]:
df.duplicated().sum()

np.int64(0)

In [39]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[features])

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

cosine = cosine_similarity(X_scaled)

In [43]:
cosine_similarity = pd.DataFrame(cosine, index=df['anime_id'], columns=df['anime_id'])

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

cosine = cosine_similarity(X_scaled)

In [45]:
cosine

array([[ 1.        ,  0.63104039,  0.70768492, ..., -0.66253677,
        -0.63976631, -0.48318443],
       [ 0.63104039,  1.        ,  0.99466698, ..., -0.99914699,
        -0.99993615, -0.98409242],
       [ 0.70768492,  0.99466698,  1.        , ..., -0.99807765,
        -0.99576897, -0.96052088],
       ...,
       [-0.66253677, -0.99914699, -0.99807765, ...,  1.        ,
         0.99954985,  0.97591661],
       [-0.63976631, -0.99993615, -0.99576897, ...,  0.99954985,
         1.        ,  0.982022  ],
       [-0.48318443, -0.98409242, -0.96052088, ...,  0.97591661,
         0.982022  ,  1.        ]])

In [58]:
def recommend_anime(anime_id):
    index = df[df['anime_id'] == anime_id].index[0]

    distances = sorted(
        list(enumerate(cosine[index])),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in distances[1:6]:
        print(df.iloc[i[0]]['name'])
        print(df.iloc[i[0]]['rating'])
        print(df.iloc[i[0]]['genre'])
        print(df.iloc[i[0]]['type'])

In [59]:
recommend_anime(1)

Doraemon Movie 20: Nobita no Uchuu Hyouryuuki
7.29
1291
Movie
Doraemon Movie 01: Nobita no Kyouryuu
7.4
1199
Movie
Daisetsusan no Yuusha Kibaou
7.13
1421
Special
Hyakko OVA
6.82
1676
OVA
Mobile Suit Gundam Thunderbolt: December Sky
7.92
776
Movie

In [67]:
def recommend_anime(anime_id, threshold):
    index = df[df['anime_id'] == anime_id].index[0]

    distances = sorted(
        list(enumerate(cosine[index])),
        reverse=True,
        key=lambda x: x[1]
    )
    recommended_anime = []
    for i in distances[1:]:
       if i[1] >= threshold:
        recommended_anime.append(df.iloc[i[0]]['name'])

    return recommended_anime

In [68]:
recommend_anime(1, 0.8)

['Doraemon Movie 20: Nobita no Uchuu Hyouryuuki',
 'Doraemon Movie 01: Nobita no Kyouryuu',
 'Daisetsusan no Yuusha Kibaou',
 'Hyakko OVA',
 'Mobile Suit Gundam Thunderbolt: December Sky',
 'Eyeshield 21',
 'GR: Giant Robo',
 'Trigun: Badlands Rumble',
 'Mutsu Enmei Ryuu Gaiden: Shura no Toki',
 'Wellber no Monogatari: Sisters of Wellber Zwei',
 'JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season',
 'D.Gray-man Hallow',
 'Hunter x Hunter OVA',
 'Hunter x Hunter: Greed Island Final',
 'Hellsing',
 'Gundam Build Fighters Try',
 'Dae Jang Geum: Jang Geum&#039;s Dream',
 'Tiger &amp; Bunny',
 'Owari no Seraph: Nagoya Kessen-hen',
 'Gintama: Jump Festa 2014 Special',
 'Chiisana Ahiru no Ooki na Ai no Monogatari: Ahiru no Kwak',
 'Mobile Suit Gundam Seed',
 'Persona 3 the Movie 3: Falling Down',
 'Negibouzu no Asatarou',
 'City Hunter 2',
 'Ramayana: The Legend of Prince Rama',
 'Tales of Phantasia The Animation',
 'Prince of Tennis: The National Tournament',
 'Code Geass: Boukoku no Akito 3 - Kagayaku Mono Ten yori Otsu',
 'Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s',
 'Kyoukaisenjou no Horizon II',
 'Lupin III: The Last Job',
 'Kekkai Sensen',
 'Seikai no Senki Special',
 'Prince of Tennis: The National Tournament Semifinals',
 'Mahou Sensei Negima! Anime Final',
 'Hakuouki Movie 1: Kyoto Ranbu',
 'The Big O',
 'Dirty Pair: The Movie',
 'Hulu Xiongdi',
 'Mobile Suit Gundam Wing: Endless Waltz Movie',
 'Digimon Tamers: Bousou Digimon Tokkyuu',
 'Durarara!! Specials',
 'Mirai Shounen Conan 2: Taiga Daibouken',
 'Chikyuu Bouei Kigyou Dai-Guard',
 'Musekinin Kanchou Tylor OVA',
 'Katanagatari',
 'Meiken Lassie',
 'Astarotte no Omocha!',
 'Doraemon Movie 13: Nobita to Kumo no Oukoku',
 'Tengen Toppa Gurren Lagann',
 'Shakugan no Shana Movie Special',
 'The Legend of Huainanzi 2nd Season',
 'Kino no Tabi: The Beautiful World',
 'Kagee Aesop Monogatari',
 '91 Days',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen',
 'Bishoujo Senshi Sailor Moon: Sailor Stars - Hero Club',
 'Vampire Hunter D (2000)',
 'Uchuu no Stellvia',
 'Mardock Scramble: The Second Combustion',
 'Doraemon Movie 08: Nobita to Ryuu no Kishi',
 'Doraemon Movie 36: Shin Nobita no Nippon Tanjou',
 'Dragon Ball Z Movie 05: Tobikkiri no Saikyou tai Saikyou',
 'Fullmetal Alchemist: Reflections',
 'Ayashi no Ceres',
 'Kemono no Souja Erin: Soushuuhen',
 'Di Gi Charat Natsuyasumi Special',
 'Phantom: Requiem for the Phantom Picture Drama',
 'Otanoshimi Anime Gekijou',
 'Dorimogu Daa!!',
 'Speed Grapher',
 'Code Geass: Boukoku no Akito 4 - Nikushimi no Kioku Kara',
 'Angel Beats!',
 'Ajin OVA',
 'Uchuu Senkan Yamato 2199: Hoshimeguru Hakobune',
 'Tsukuyomi: Moon Phase Special',
 'Magi: The Kingdom of Magic',
 'Mushrambo',
 'Hunter x Hunter',
 'Minami no Niji no Lucy',
 'Noragami Aragoto',
 'Dogs: Bullets &amp; Carnage',
 'Captain Tsubasa: Road to 2002',
 'Canaan',
 'Di Gi Charat Christmas Special',
 'Fumiko no Kokuhaku',
 'Hentai Ouji to Warawanai Neko.: Henneko BBS',
 'Inazuma Eleven Go: TCG CM NG-shuu',
 'Yuu☆Yuu☆Hakusho: Mu Mu Hakusho',
 'Bonobono',
 'Mak Dau Xiang Dang Dang',
 'Tengen Toppa Gurren Lagann Movie: Gurren-hen',
 'Trinity Blood',
 'Guilty Crown',
 'Mobile Suit Gundam Wing',
 'Mobile Suit Gundam Wing: Endless Waltz',
 'Soukou Kihei Votoms',
 'Break Blade 1: Kakusei no Toki',
 'Prince of Tennis',
 'Witchblade',
 'Gregory Horror Show: The Last Train',
 'The Rose and Women of Versailles',
 'Donten ni Warau',
 'Gintama: Jump Festa 2015 Special',
 'Kiteretsu Daihyakka',
 'Saiunkoku Monogatari Soushuuhen',
 'Pokemon 3D Adventure: Mew wo Sagase!',
 'Redline',
 'Kachou Ouji',
 'Druaga no Tou: The Aegis of Uruk',
 'Gintama: Dai Hanseikai',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Mermaid Melody Pichi Pichi Pitch Pure',
 'Otogizoushi',
 'Kubikiri Cycle: Aoiro Savant to Zaregototsukai',
 'Yuu☆Yuu☆Hakusho',
 'Rakudai Kishi no Cavalry',
 'Senki Zesshou Symphogear G: In the Distance, That Day, When the Star Became Music...',
 'Senki Zesshou Symphogear GX: Believe in Justice and Hold a Determination to Fist.',
 'Aoi Blink',
 'Mo Jing Lieren 2nd Season',
 'Shen Ming Zhi Zhou',
 'Yong Zhe Da Mao Xian 2nd Season',
 'Daisougen no Chiisana Tenshi: Bush Baby',
 'Hokuto no Ken',
 'Towa no Quon 2: Konton no Ranbu',
 'Baccano! Specials',
 'Slayers Excellent',
 'Hakuouki Movie 2: Shikon Soukyuu',
 'C: The Money of Soul and Possibility Control',
 'Mahoutsukai Precure! Movie',
 'Shijou Saikyou no Deshi Kenichi',
 'Mazinkaiser SKL',
 'Stranger: Mukou Hadan',
 'Sengoku Basara Two',
 'Pokemon XY: Sora no Hahen',
 'JoJo no Kimyou na Bouken (TV)',
 'Doraemon Movie 10: Nobita no Nippon Tanjou',
 'Doraemon Movie 23: Nobita to Robot Kingdom',
 'Hunter x Hunter: Greed Island',
 'Asura Cryin&#039; 2',
 'Mahou Senshi Louie',
 'Rakuen Tsuihou: Expelled from Paradise',
 'Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi',
 'Digimon Adventure 02: Diablomon no Gyakushuu',
 'Lupin III vs. Detective Conan: The Movie',
 'Doraemon Movie 02: Nobita no Uchuu Kaitakushi',
 'Prince of Tennis: The Two Samurai, The First Game',
 'Slayers Premium',
 'Black Bullet',
 'Doraemon Movie 19: Nobita no Nankai Daibouken',
 'Working&#039;!! Announcement Specials',
 'Captain Tsubasa J',
 'Pokemon Black and White 2: Introduction Movie',
 'Fushigi Yuugi OVA',
 'Gintama: Shinyaku Benizakura-hen',
 'Solty Rei',
 'Mobile Suit Gundam Thunderbolt',
 'Dirty Pair',
 'Mahou Shoujo-tai Arusu',
 'Doraemon Movie 30: Nobita no Ningyo Daikaisen',
 'Doraemon Movie 32: Nobita to Kiseki no Shima - Animal Adventure',
 'Medarot',
 'Slayers Revolution',
 'Chuuzumou',
 'Di Gi Charat Tsuyu Specials',
 'Madan no Ou to Vanadis: Tigre-kun to Vanadi-chu',
 'Jungle Kurobee',
 'Only You: Viva! Cabaret Club',
 'Shingeki no Kyojin OVA',
 'Elfen Lied',
 'Ansatsu Kyoushitsu (TV)',
 'Shukufuku no Campanella: La Campanella Della Benedizione',
 'Cross Ange: Tenshi to Ryuu no Rondo',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2',
 'Pokemon: Mizu no Miyako no Mamorigami Latias to Latios',
 'Ie Naki Ko Remi Specials (2001)',
 'Redline Pilot',
 'Full Metal Panic? Fumoffu',
 'Texhnolyze',
 'Sobakasu Pucchi',
 'Toaru Majutsu no Index',
 'Hakkenden: Touhou Hakken Ibun 2nd Season',
 'Sengoku Basara Movie: The Last Party',
 'Dirty Pair OVA',
 'Zegapain',
 'Coo: Tooi Umi kara Kita Coo',
 'Saint Seiya: Meiou Hades Elysion-hen',
 'Hatenkou Yuugi',
 'Persona 3 the Movie 1: Spring of Birth',
 'Tiger &amp; Bunny Movie 2: The Rising',
 'Gungrave',
 'Astarotte no Omocha! EX',
 'Captain Tsubasa',
 'Ao no Exorcist',
 'Accel World',
 'Kikou Senki Dragonar',
 'Doraemon Movie 16: Nobita no Sousei Nikki',
 'Dan Doh!!',
 'Code Geass: Boukoku no Akito 1 - Yokuryuu wa Maiorita',
 'Manie-Manie: Meikyuu Monogatari',
 'Bleach',
 'Shiawase Sou no Okojo-san',
 'Blue Gender',
 'Heroic Age',
 'Tokyo Ghoul',
 'Toaru Majutsu no Index: Endymion no Kiseki',
 'City Hunter',
 'Tibet Inu Monogatari',
 'Boruto: Naruto the Movie',
 'Break Blade 2: Ketsubetsu no Michi',
 'Kazemakase Tsukikage Ran',
 'Kill la Kill',
 'Chou Denji Robo Combattler V',
 'Ginga Kikoutai Majestic Prince',
 'Kara no Kyoukai 6: Boukyaku Rokuon',
 'Yuki no Joou',
 'Gintama: Shiroyasha Koutan',
 'Pokemon: Maboroshi no Pokemon Lugia Bakutan',
 'Kakumeiki Valvrave 2nd Season',
 'Initial D Fourth Stage',
 'Mardock Scramble: The Third Exhaust',
 'Kaitou Joker 2nd Season',
 'Nanatsu no Taizai',
 'Nurarihyon no Mago: Sennen Makyou',
 'Doraemon Movie 12: Nobita no Dorabian Nights',
 'Kaitou Joker 4th Season',
 'Ketsuekigata-kun!',
 'Doushitemo Eto ni Hairitai',
 'Mirai Nikki',
 'YAT Anshin! Uchuu Ryokou',
 'Seikai no Monshou Special',
 'Shijou Saikyou no Deshi Kenichi OVA',
 'Strike Witches Movie',
 'Kenran Butou Sai: The Mars Daybreak',
 'Mononoke Hime',
 'Appleseed Saga Ex Machina',
 'Kumo no You ni Kaze no You ni',
 'Initial D First Stage',
 'Ou Dorobou Jing',
 'Dimension W',
 'Tamala 2010: A Punk Cat in Space',
 'Cencoroll',
 'Nurarihyon no Mago OVA',
 'Aoki Hagane no Arpeggio: Ars Nova',
 'Sengoku Basara',
 'Doraemon Movie 03: Nobita no Daimakyou',
 'Cosmic Baton Girl Comet-san',
 'Brigadoon: Marin to Melan',
 'Wagamama☆Fairy Mirumo de Pon!',
 'Long Zai Na Li',
 'Dragon League',
 'Kokoro Toshokan',
 'Pokemon the Movie XY&amp;Z: Volcanion to Karakuri no Magiana',
 'Mobile Suit Gundam Seed Special Edition',
 'Digimon Tamers: Boukensha-tachi no Tatakai',
 'Tytania',
 'Blood+',
 'Ao no Exorcist Movie',
 'Tsubasa: Tokyo Revelations',
 'Ajin',
 'Senki Zesshou Symphogear G: In the Distance, That Day, When the Star Became Music... Specials',
 'Toaru Kagaku no Railgun S: Daiji na Koto wa Zenbu Sentou ni Osowatta',
 'Hyakujuu-Ou GoLion',
 'Ghost in the Shell (2015)',
 'Transformers: Choujin Master Force',
 'Mobile Suit Gundam 00 Special Edition',
 'Tom Sawyer no Bouken',
 'Pokemon the Movie XY: Ring no Choumajin Hoopa',
 '.hack//Roots',
 'Aldnoah.Zero',
 'JoJo no Kimyou na Bouken: Diamond wa Kudakenai',
 'Marco: Haha wo Tazunete Sanzenri',
 'Zetsuen no Tempest',
 'Psycho-Pass 2',
 'One Piece',
 'Towa no Quon 1: Utakata no Kaben',
 'Tatsu no Ko Tarou',
 'City Hunter 3',
 'Escaflowne',
 'Samurai Champloo',
 'Moetan',
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Dragon Ball Z Movie 09: Ginga Girigiri!! Bucchigiri no Sugoi Yatsu',
 'Terra e... (TV)',
 'Darker than Black: Ryuusei no Gemini',
 'Mobile Suit Gundam 00 The Movie: A Wakening of the Trailblazer',
 'Sora wo Kakeru Shoujo',
 'Grappler Baki: Saidai Tournament-hen',
 'Mashin Eiyuuden Wataru',
 'Kyoro-chan',
 'Seton Doubutsuki',
 'One Piece: Kinkyuu Kikaku One Piece Kanzen Kouryakuhou',
 'Toaru Kagaku no Railgun: Misaka-san wa Ima Chuumoku no Mato desukara',
 'Persona 3 the Movie 2: Midsummer Knight&#039;s Dream',
 'Doraemon Movie 24: Nobita to Fushigi Kaze Tsukai',
 'Aoki Hagane no Arpeggio: Ars Nova DC',
 'Ajin Part 2: Shoutotsu',
 'Akame ga Kill! Theater',
 'Di Gi Charat: Hoshi no Tabi',
 'Medaka no Gakkou',
 'Tonari no Tokoro',
 'Kamikaze Kaitou Jeanne',
 'Precure All Stars Movie DX3: Mirai ni Todoke! Sekai wo Tsunagu☆Nijiiro no Hana',
 'Chirin no Suzu',
 'Ouritsu Uchuugun: Honneamise no Tsubasa',
 'Mnemosyne: Mnemosyne no Musume-tachi',
 'Sangokushi',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa',
 'Slayers: The Motion Picture',
 'World Destruction: Sekai Bokumetsu no Rokunin',
 'Love Live! School Idol Project: μ&#039;s →NEXT LoveLive! 2014 - Endless Parade Makuai Drama',
 'Moyashimon: Kin Gekijou Deluxe',
 'Senjou no Valkyria: SenVal Theater',
 'Monkey King: Hero Is Back',
 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season',
 'Irregular Hunter X: The Day of Sigma',
 'Shakugan no Shana II (Second)',
 'One Piece: Nenmatsu Tokubetsu Kikaku! Mugiwara no Luffy Oyabun Torimonochou',
 'Muku Hatojuu no Meiken Monogatari',
 'Dead Leaves',
 'Hells',
 'Popee the Performer',
 'Trigun',
 'Black Jack (TV): Hizouban Specials',
 'Doraemon Movie 34: Shin Nobita no Daimakyou - Peko to 5-nin no Tankentai',
 'Sweat Punch',
 'Lupin III: Sweet Lost Night - Mahou no Lamp wa Akumu no Yokan',
 'Isekai no Seikishi Monogatari',
 'Hakkenden: Touhou Hakken Ibun',
 'Noragami',
 'Tenchi Muyou! Ryououki 4th Season',
 'Digimon Adventure Movie',
 'Utawarerumono',
 'Break Blade 3: Kyoujin no Ato',
 'Kaitou Joker 3rd Season',
 'Majime ni Fumajime Kaiketsu Zorori',
 '1000-nen Joou: Queen Millennia',
 'Kyouryuu Boukenki Jura Tripper',
 'Jikuu Boukenki Zentrix',
 'Tenjou Tenge: The Past Chapter',
 'Arslan Senki (TV) OVA',
 'Ansatsu Kyoushitsu (TV) 2nd Season: Kagaijugyou-hen',
 'Rurouni Kenshin Special',
 'Mardock Scramble: The First Compression',
 'Berserk',
 'Michitekuru Toki no Mukou ni',
 'JoJo no Kimyou na Bouken: Adventure',
 'Doraemon Movie 11: Nobita to Animal Planet',
 'Naruto: Shippuuden',
 'City Hunter &#039;91',
 'Mermaid Melody Pichi Pichi Pitch',
 'Doraemon Movie 29: Shin Nobita no Uchuu Kaitakushi',
 'Strike the Blood II',
 'Hakuouki Hekketsuroku',
 'Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation',
 'Neon Genesis Evangelion',
 'Hakuouki Sekkaroku',
 'Mahou Shoujo Lyrical Nanoha A&#039;s',
 'Initial D Fifth Stage',
 'Hokuto no Ken: Toki-den',
 'Fate/stay night Movie: Unlimited Blade Works',
 'Deadman Wonderland',
 'Naruto: Shippuuden Movie 2 - Kizuna',
 'Ajin Part 1: Shoudou',
 'Evangelion: 3.0 You Can (Not) Redo',
 'Slayers Great',
 'Boku no Hero Academia',
 'Yume de Aetara (TV)',
 'Rurouni Kenshin: Meiji Kenkaku Romantan',
 'Yu☆Gi☆Oh! Arc-V',
 'Usavich II',
 'Scrapped Princess',
 'Di Gi Charat Ohanami Special',
 'Sword Art Online: Sword Art Offline - Extra Edition',
 'Anime Koukyoushi: Jungle Taitei',
 'Owari no Seraph',
 'Pokemon 3D Adventure 2: Pikachu no Kaitei Daibouken',
 'Heavy Object',
 'Nurarihyon no Mago',
 'YAT Anshin! Uchuu Ryokou 2',
 'Chrno Crusade',
 'Final Fantasy VII: Advent Children',
 'Negima!?',
 'KanColle Movie',
 'Magic Knight Rayearth',
 'Sword Art Online II: Sword Art Offline II',
 'Jam the Housnail',
 'Shika to Kanta',
 'Fate/stay night',
 'Durarara!!x2 Ten: Onoroke Chakapoko',
 'Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa',
 'Hakuouki Reimeiroku Tokuten Disc',
 'Detective Conan OVA 03: Conan and Heiji and the Vanished Boy',
 'Hellsing I: Digest for Freaks',
 'Initial D Second Stage',
 'Dokidoki Densetsu: Mahoujin Guru Guru',
 'Slayers Return',
 'Transformers Victory',
 'Shimajirou to Ehon no Kuni',
 'Black Jack 21',
 'God Eater',
 'Yu☆Gi☆Oh! 5D&#039;s',
 'Slayers Gorgeous',
 'Sennen Joyuu',
 'Chikyuu Shoujo Arjuna',
 'Dragon Ball Z Movie 07: Kyokugen Battle!! Sandai Super Saiyajin',
 'Kyousou Giga (TV)',
 'Tokyo Ghoul: &quot;Jack&quot;',
 'Katekyo Hitman Reborn!',
 'Karas',
 'Magi: The Labyrinth of Magic',
 'Noragami Aragoto OVA',
 'Tenjou Tenge: The Ultimate Fight',
 'Fight Ippatsu! Juuden-chan!! Specials',
 'Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen',
 'Teach',
 'Baccano!',
 'Street Fighter II V',
 'Love Hina Haru Special: Kimi Sakura Chiru Nakare!!',
 'Inferno Cop',
 'Break Blade 4: Sanka no Chi',
 'Shakugan no Shana',
 'Tetsuwan Birdy Decode:02',
 'Seimei no Kagaku: Micro Patrol',
 'Dragon Ball: Super Saiya-jin Zetsumetsu Keikaku',
 'One Punch Man Specials',
 'Black Clover',
 'Code Geass: Hangyaku no Lelouch Special Edition Black Rebellion',
 'Star Driver: Kagayaki no Takuto',
 'Final Approach',
 'Rokudenashi Blues',
 'Shadow Skill: Eigi',
 'Pandane to Tamago-hime',
 'Erementar Gerad',
 'Shakugan no Shana III (Final)',
 'Magi: Sinbad no Bouken (TV)',
 'Panyo Panyo Di Gi Charat',
 'Seirei no Moribito',
 'Yousei Florence',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'One Punch Man: Road to Hero',
 'Toaru Majutsu no Index II',
 'Sengoku Basara Two: Ryuko, Itadaki no Chikai! Atsuki Mirai e Kakeru Tamashii!!',
 'Kill la Kill Special',
 'Fushigi Yuugi: Eikouden',
 'Mobile Suit Gundam 00 Second Season',
 'Ganbare Swimmy',
 'JoJo no Kimyou na Bouken: Stardust Crusaders',
 'Tekkon Kinkreet',
 'Btooom!',
 'Fractale',
 'Sanzoku no Musume Ronja',
 'Doraemon Movie 07: Nobita to Tetsujin Heidan',
 'Higashi no Eden',
 'Super Robot Taisen OG: The Inspector',
 'Mahou Shoujo Lyrical Nanoha: The Movie 1st',
 'Pygmalio',
 'Ou Dorobou Jing in Seventh Heaven',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
 'Baby Baachan',
 'Mirai Shounen Conan (Movie)',
 'Kuroshitsuji',
 'Gad Guard',
 'Yuusha-Ou GaoGaiGar Final Grand Glorious Gathering',
 'Hayate no Gotoku!!',
 'FLCL',
 'Dae Jang Geum: Jang Geum&#039;s Dream 2',
 '.hack//Sign',
 'Kuromukuro',
 'Fate/Zero: Onegai! Einzbern Soudanshitsu',
 'Tales of Gekijou',
 'Shikabane Hime: Kuro',
 'Kiddy Grade: Truth Dawn',
 'Gintama Movie: Shinyaku Benizakura-hen',
 'Anime 80-nichikan Sekai Isshuu',
 'One Piece Film: Strong World',
 'Doraemon Movie 33: Nobita no Himitsu Dougu Museum',
 'Yume no Crayon Oukoku',
 'Geunyeoneun Yeppeotda',
 'Akira',
 'Nanatsu no Umi no Tico Specials',
 'Spriggan',
 'Sei Juushi Bismarck',
 'Beet the Vandel Buster',
 'El Hazard: The Magnificent World',
 'Beelzebub',
 'Phantom: Requiem for the Phantom',
 'Gintama: Yorinuki Gintama-san on Theater 2D',
 'Deltora Quest',
 'Mobile Suit Gundam 00',
 'Akatsuki no Yona OVA',
 'Shingeki no Kyojin Movie 1: Guren no Yumiya',
 'Happy☆Lucky Bikkuriman',
 'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture',
 'Great Mazinger',
 'Sidonia no Kishi Movie',
 'Final Fantasy VII: Advent Children - Venice Film Festival Footage',
 'Mai-HiME: Kuro no Mai/Saigo no Bansan',
 'Ichigo Ichie: Kimi no Kotoba',
 'Midnight Horror School',
 'Noramimi',
 'Metal Fight Beyblade 4D',
 'Angel Beats! Specials',
 'Imawa no Kuni no Alice (OVA)',
 'Kiddy Grade: Maelstrom',
 'Elsword: El Lady',
 'Break Blade 6: Doukoku no Toride',
 'Durarara!!x2 Ketsu: Dufufufu!!',
 'Gift: Eternal Rainbow',
 'Senjou no Valkyria',
 'NG Knight Ramune &amp; 40',
 'Kara no Kyoukai 3: Tsuukaku Zanryuu',
 'One Piece Film: Z',
 'Groove Adventure Rave',
 'Biohazard: Damnation',
 'Mirai Nikki Redial',
 'Guilty Crown Kiseki: Reassortment',
 'Mazinkaiser: Shitou! Ankoku Dai Shogun',
 'Towa no Quon 3: Mugen no Renza',
 'Slayers Special',
 'Slayers Evolution-R',
 'Juuni Kokuki',
 'Doraemon',
 'InuYasha: Guren no Houraijima',
 'Buddy Complex: Kanketsu-hen - Ano Sora ni Kaeru Mirai de',
 'Mobile Suit Gundam 00: Tenshitachi no Kiseki',
 'Akazukin Chacha',
 'Tenchi Muyou! Ryououki',
 'Mirai Shounen Conan: Tokubetsu-hen - Kyodaiki Gigant no Fukkatsu',
 'The Last: Naruto the Movie',
 'Hokuto no Ken 2',
 'Gensoumaden Saiyuuki: Kibou no Zaika',
 'Muumin',
 'Jormungand: Perfect Order',
 'Kara no Kyoukai Remix: Gate of Seventh Heaven',
 'Innocent Venus',
 'Elf wo Karu Mono-tachi II',
 'Tsuyoshi Shikkari Shinasai: Tsuyoshi no Time Machine de Shikkari Shinasai',
 'Dragon Ball Z',
 'Tsubasa: Shunraiki',
 'Elf wo Karu Mono-tachi',
 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen',
 'Macross F: Close Encounter - Deculture Edition',
 'Kakumeiki Valvrave',
 'Gongitsune',
 'Top wo Nerae 2! Diebuster',
 'One Piece Movie 7: Karakuri-jou no Mecha Kyohei',
 'Bleach Movie 4: Jigoku-hen',
 'Detective Conan OVA 05: The Target is Kogoro! The Detective Boys&#039; Secret Investigation',
 'InuYasha: Kanketsu-hen',
 'Vandread: The Second Stage',
 'High School Fleet',
 'Line Offline: Salaryman',
 'Shigofumi Picture Drama',
 'Nyani ga Nyandaa Nyandaa Kamen',
 'Code Geass: Boukoku no Akito 2 - Hikisakareshi Yokuryuu',
 'Top wo Nerae! Gunbuster',
 'Detective Conan OVA 01: Conan vs. Kid vs. Yaiba',
 'Kinnikuman',
 'Peter Pan no Bouken',
 'Mashin Eiyuuden Wataru 2',
 'Detective Conan Movie 19: The Hellfire Sunflowers',
 'Yoroiden Samurai Troopers Gaiden',
 'El Hazard: The Wanderers',
 'Black★Rock Shooter',
 'Full Metal Panic!',
 'Heartcatch Precure!',
 'Mahoujin Guru Guru Movie',
 'Hakuouki OVA',
 'Shakugan no Shana Movie',
 'Fullmetal Alchemist: Brotherhood',
 'Fushigi no Umi no Nadia Specials',
 'Naruto',
 'Kaze no Stigma',
 'Detective Conan OVA 07: A Challenge from Agasa! Agasa vs. Conan and the Detective Boys',
 'Noblesse: Awakening',
 'Giniro no Kami no Agito',
 'Naruto Movie 1: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo!',
 'Jungle Taitei: Susume Leo!',
 'Omae Umasou da na',
 'Shounen Onmyouji',
 'Log Horizon',
 'Sakura Taisen',
 'Sakura Taisen: Gouka Kenran',
 'Shin Koihime†Musou: Otome Tairan',
 'Sangokushi II: Amakakeru Otoko-tachi',
 'Captain Harlock',
 'Jungle Book Shounen Mowgli',
 'Manga Sekai Mukashibanashi',
 'Nils no Fushigi na Tabi',
 'RD Sennou Chousashitsu',
 'Fullmetal Alchemist',
 'Macross Δ',
 'Dragon Ball Z Movie 06: Gekitotsu!! 100-oku Power no Senshi-tachi',
 'Pokemon Fushigi no Dungeon: Sora no Tankentai - Toki to Yami wo Meguru Saigo no Bouken',
 'One Piece Film: Gold',
 'Ginga Nagareboshi Gin',
 'Initial D Third Stage',
 'Oyayubi Hime Monogatari',
 'Shin Captain Tsubasa',
 'New Prince of Tennis OVA vs. Genius10',
 'Hakuouki Reimeiroku',
 'World Trigger',
 'Dance in the Vampire Bund',
 'Mobile Suit Gundam',
 'One Piece: Mamore! Saigo no Dai Butai',
 'Bungou Stray Dogs',
 'Mob Psycho 100',
 'Tokyo Ghoul: &quot;Pinto&quot;',
 'Mai-Otome Zwei',
 'Bounen no Xamdou',
 'D.Gray-man',
 'Mai Mai Shinko to Sennen no Mahou',

In [69]:
recommend_anime(1, 0.9)

['Doraemon Movie 20: Nobita no Uchuu Hyouryuuki',
 'Doraemon Movie 01: Nobita no Kyouryuu',
 'Daisetsusan no Yuusha Kibaou',
 'Hyakko OVA',
 'Mobile Suit Gundam Thunderbolt: December Sky',
 'Eyeshield 21',
 'GR: Giant Robo',
 'Trigun: Badlands Rumble',
 'Mutsu Enmei Ryuu Gaiden: Shura no Toki',
 'Wellber no Monogatari: Sisters of Wellber Zwei',
 'JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season',
 'D.Gray-man Hallow',
 'Hunter x Hunter OVA',
 'Hunter x Hunter: Greed Island Final',
 'Hellsing',
 'Gundam Build Fighters Try',
 'Dae Jang Geum: Jang Geum&#039;s Dream',
 'Tiger &amp; Bunny',
 'Owari no Seraph: Nagoya Kessen-hen',
 'Gintama: Jump Festa 2014 Special',
 'Chiisana Ahiru no Ooki na Ai no Monogatari: Ahiru no Kwak',
 'Mobile Suit Gundam Seed',
 'Persona 3 the Movie 3: Falling Down',
 'Negibouzu no Asatarou',
 'City Hunter 2',
 'Ramayana: The Legend of Prince Rama',
 'Tales of Phantasia The Animation',
 'Prince of Tennis: The National Tournament',
 'Code Geass: Boukoku no Akito 3 - Kagayaku Mono Ten yori Otsu',
 'Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s',
 'Kyoukaisenjou no Horizon II',
 'Lupin III: The Last Job',
 'Kekkai Sensen',
 'Seikai no Senki Special',
 'Prince of Tennis: The National Tournament Semifinals',
 'Mahou Sensei Negima! Anime Final',
 'Hakuouki Movie 1: Kyoto Ranbu',
 'The Big O',
 'Dirty Pair: The Movie',
 'Hulu Xiongdi',
 'Mobile Suit Gundam Wing: Endless Waltz Movie',
 'Digimon Tamers: Bousou Digimon Tokkyuu',
 'Durarara!! Specials',
 'Mirai Shounen Conan 2: Taiga Daibouken',
 'Chikyuu Bouei Kigyou Dai-Guard',
 'Musekinin Kanchou Tylor OVA',
 'Katanagatari',
 'Meiken Lassie',
 'Astarotte no Omocha!',
 'Doraemon Movie 13: Nobita to Kumo no Oukoku',
 'Tengen Toppa Gurren Lagann',
 'Shakugan no Shana Movie Special',
 'The Legend of Huainanzi 2nd Season',
 'Kino no Tabi: The Beautiful World',
 'Kagee Aesop Monogatari',
 '91 Days',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen',
 'Bishoujo Senshi Sailor Moon: Sailor Stars - Hero Club',
 'Vampire Hunter D (2000)',
 'Uchuu no Stellvia',
 'Mardock Scramble: The Second Combustion',
 'Doraemon Movie 08: Nobita to Ryuu no Kishi',
 'Doraemon Movie 36: Shin Nobita no Nippon Tanjou',
 'Dragon Ball Z Movie 05: Tobikkiri no Saikyou tai Saikyou',
 'Fullmetal Alchemist: Reflections',
 'Ayashi no Ceres',
 'Kemono no Souja Erin: Soushuuhen',
 'Di Gi Charat Natsuyasumi Special',
 'Phantom: Requiem for the Phantom Picture Drama',
 'Otanoshimi Anime Gekijou',
 'Dorimogu Daa!!',
 'Speed Grapher',
 'Code Geass: Boukoku no Akito 4 - Nikushimi no Kioku Kara',
 'Angel Beats!',
 'Ajin OVA',
 'Uchuu Senkan Yamato 2199: Hoshimeguru Hakobune',
 'Tsukuyomi: Moon Phase Special',
 'Magi: The Kingdom of Magic',
 'Mushrambo',
 'Hunter x Hunter',
 'Minami no Niji no Lucy',
 'Noragami Aragoto',
 'Dogs: Bullets &amp; Carnage',
 'Captain Tsubasa: Road to 2002',
 'Canaan',
 'Di Gi Charat Christmas Special',
 'Fumiko no Kokuhaku',
 'Hentai Ouji to Warawanai Neko.: Henneko BBS',
 'Inazuma Eleven Go: TCG CM NG-shuu',
 'Yuu☆Yuu☆Hakusho: Mu Mu Hakusho',
 'Bonobono',
 'Mak Dau Xiang Dang Dang',
 'Tengen Toppa Gurren Lagann Movie: Gurren-hen',
 'Trinity Blood',
 'Guilty Crown',
 'Mobile Suit Gundam Wing',
 'Mobile Suit Gundam Wing: Endless Waltz',
 'Soukou Kihei Votoms',
 'Break Blade 1: Kakusei no Toki',
 'Prince of Tennis',
 'Witchblade',
 'Gregory Horror Show: The Last Train',
 'The Rose and Women of Versailles',
 'Donten ni Warau',
 'Gintama: Jump Festa 2015 Special',
 'Kiteretsu Daihyakka',
 'Saiunkoku Monogatari Soushuuhen',
 'Pokemon 3D Adventure: Mew wo Sagase!',
 'Redline',
 'Kachou Ouji',
 'Druaga no Tou: The Aegis of Uruk',
 'Gintama: Dai Hanseikai',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Mermaid Melody Pichi Pichi Pitch Pure',
 'Otogizoushi',
 'Kubikiri Cycle: Aoiro Savant to Zaregototsukai',
 'Yuu☆Yuu☆Hakusho',
 'Rakudai Kishi no Cavalry',
 'Senki Zesshou Symphogear G: In the Distance, That Day, When the Star Became Music...',
 'Senki Zesshou Symphogear GX: Believe in Justice and Hold a Determination to Fist.',
 'Aoi Blink',
 'Mo Jing Lieren 2nd Season',
 'Shen Ming Zhi Zhou',
 'Yong Zhe Da Mao Xian 2nd Season',
 'Daisougen no Chiisana Tenshi: Bush Baby',
 'Hokuto no Ken',
 'Towa no Quon 2: Konton no Ranbu',
 'Baccano! Specials',
 'Slayers Excellent',
 'Hakuouki Movie 2: Shikon Soukyuu',
 'C: The Money of Soul and Possibility Control',
 'Mahoutsukai Precure! Movie',
 'Shijou Saikyou no Deshi Kenichi',
 'Mazinkaiser SKL',
 'Stranger: Mukou Hadan',
 'Sengoku Basara Two',
 'Pokemon XY: Sora no Hahen',
 'JoJo no Kimyou na Bouken (TV)',
 'Doraemon Movie 10: Nobita no Nippon Tanjou',
 'Doraemon Movie 23: Nobita to Robot Kingdom',
 'Hunter x Hunter: Greed Island',
 'Asura Cryin&#039; 2',
 'Mahou Senshi Louie',
 'Rakuen Tsuihou: Expelled from Paradise',
 'Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi',
 'Digimon Adventure 02: Diablomon no Gyakushuu',
 'Lupin III vs. Detective Conan: The Movie',
 'Doraemon Movie 02: Nobita no Uchuu Kaitakushi',
 'Prince of Tennis: The Two Samurai, The First Game',
 'Slayers Premium',
 'Black Bullet',
 'Doraemon Movie 19: Nobita no Nankai Daibouken',
 'Working&#039;!! Announcement Specials',
 'Captain Tsubasa J',
 'Pokemon Black and White 2: Introduction Movie',
 'Fushigi Yuugi OVA',
 'Gintama: Shinyaku Benizakura-hen',
 'Solty Rei',
 'Mobile Suit Gundam Thunderbolt',
 'Dirty Pair',
 'Mahou Shoujo-tai Arusu',
 'Doraemon Movie 30: Nobita no Ningyo Daikaisen',
 'Doraemon Movie 32: Nobita to Kiseki no Shima - Animal Adventure',
 'Medarot',
 'Slayers Revolution',
 'Chuuzumou',
 'Di Gi Charat Tsuyu Specials',
 'Madan no Ou to Vanadis: Tigre-kun to Vanadi-chu',
 'Jungle Kurobee',
 'Only You: Viva! Cabaret Club',
 'Shingeki no Kyojin OVA',
 'Elfen Lied',
 'Ansatsu Kyoushitsu (TV)',
 'Shukufuku no Campanella: La Campanella Della Benedizione',
 'Cross Ange: Tenshi to Ryuu no Rondo',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2',
 'Pokemon: Mizu no Miyako no Mamorigami Latias to Latios',
 'Ie Naki Ko Remi Specials (2001)',
 'Redline Pilot',
 'Full Metal Panic? Fumoffu',
 'Texhnolyze',
 'Sobakasu Pucchi',
 'Toaru Majutsu no Index',
 'Hakkenden: Touhou Hakken Ibun 2nd Season',
 'Sengoku Basara Movie: The Last Party',
 'Dirty Pair OVA',
 'Zegapain',
 'Coo: Tooi Umi kara Kita Coo',
 'Saint Seiya: Meiou Hades Elysion-hen',
 'Hatenkou Yuugi',
 'Persona 3 the Movie 1: Spring of Birth',
 'Tiger &amp; Bunny Movie 2: The Rising',
 'Gungrave',
 'Astarotte no Omocha! EX',
 'Captain Tsubasa',
 'Ao no Exorcist',
 'Accel World',
 'Kikou Senki Dragonar',
 'Doraemon Movie 16: Nobita no Sousei Nikki',
 'Dan Doh!!',
 'Code Geass: Boukoku no Akito 1 - Yokuryuu wa Maiorita',
 'Manie-Manie: Meikyuu Monogatari',
 'Bleach',
 'Shiawase Sou no Okojo-san',
 'Blue Gender',
 'Heroic Age',
 'Tokyo Ghoul',
 'Toaru Majutsu no Index: Endymion no Kiseki',
 'City Hunter',
 'Tibet Inu Monogatari',
 'Boruto: Naruto the Movie',
 'Break Blade 2: Ketsubetsu no Michi',
 'Kazemakase Tsukikage Ran',
 'Kill la Kill',
 'Chou Denji Robo Combattler V',
 'Ginga Kikoutai Majestic Prince',
 'Kara no Kyoukai 6: Boukyaku Rokuon',
 'Yuki no Joou',
 'Gintama: Shiroyasha Koutan',
 'Pokemon: Maboroshi no Pokemon Lugia Bakutan',
 'Kakumeiki Valvrave 2nd Season',
 'Initial D Fourth Stage',
 'Mardock Scramble: The Third Exhaust',
 'Kaitou Joker 2nd Season',
 'Nanatsu no Taizai',
 'Nurarihyon no Mago: Sennen Makyou',
 'Doraemon Movie 12: Nobita no Dorabian Nights',
 'Kaitou Joker 4th Season',
 'Ketsuekigata-kun!',
 'Doushitemo Eto ni Hairitai',
 'Mirai Nikki',
 'YAT Anshin! Uchuu Ryokou',
 'Seikai no Monshou Special',
 'Shijou Saikyou no Deshi Kenichi OVA',
 'Strike Witches Movie',
 'Kenran Butou Sai: The Mars Daybreak',
 'Mononoke Hime',
 'Appleseed Saga Ex Machina',
 'Kumo no You ni Kaze no You ni',
 'Initial D First Stage',
 'Ou Dorobou Jing',
 'Dimension W',
 'Tamala 2010: A Punk Cat in Space',
 'Cencoroll',
 'Nurarihyon no Mago OVA',
 'Aoki Hagane no Arpeggio: Ars Nova',
 'Sengoku Basara',
 'Doraemon Movie 03: Nobita no Daimakyou',
 'Cosmic Baton Girl Comet-san',
 'Brigadoon: Marin to Melan',
 'Wagamama☆Fairy Mirumo de Pon!',
 'Long Zai Na Li',
 'Dragon League',
 'Kokoro Toshokan',
 'Pokemon the Movie XY&amp;Z: Volcanion to Karakuri no Magiana',
 'Mobile Suit Gundam Seed Special Edition',
 'Digimon Tamers: Boukensha-tachi no Tatakai',
 'Tytania',
 'Blood+',
 'Ao no Exorcist Movie',
 'Tsubasa: Tokyo Revelations',
 'Ajin',
 'Senki Zesshou Symphogear G: In the Distance, That Day, When the Star Became Music... Specials',
 'Toaru Kagaku no Railgun S: Daiji na Koto wa Zenbu Sentou ni Osowatta',
 'Hyakujuu-Ou GoLion',
 'Ghost in the Shell (2015)',
 'Transformers: Choujin Master Force',
 'Mobile Suit Gundam 00 Special Edition',
 'Tom Sawyer no Bouken',
 'Pokemon the Movie XY: Ring no Choumajin Hoopa',
 '.hack//Roots',
 'Aldnoah.Zero',
 'JoJo no Kimyou na Bouken: Diamond wa Kudakenai',
 'Marco: Haha wo Tazunete Sanzenri',
 'Zetsuen no Tempest',
 'Psycho-Pass 2',
 'One Piece',
 'Towa no Quon 1: Utakata no Kaben',
 'Tatsu no Ko Tarou',
 'City Hunter 3',
 'Escaflowne',
 'Samurai Champloo',
 'Moetan',
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Dragon Ball Z Movie 09: Ginga Girigiri!! Bucchigiri no Sugoi Yatsu',
 'Terra e... (TV)',
 'Darker than Black: Ryuusei no Gemini',
 'Mobile Suit Gundam 00 The Movie: A Wakening of the Trailblazer',
 'Sora wo Kakeru Shoujo',
 'Grappler Baki: Saidai Tournament-hen',
 'Mashin Eiyuuden Wataru',
 'Kyoro-chan',
 'Seton Doubutsuki',
 'One Piece: Kinkyuu Kikaku One Piece Kanzen Kouryakuhou',
 'Toaru Kagaku no Railgun: Misaka-san wa Ima Chuumoku no Mato desukara',
 'Persona 3 the Movie 2: Midsummer Knight&#039;s Dream',
 'Doraemon Movie 24: Nobita to Fushigi Kaze Tsukai',
 'Aoki Hagane no Arpeggio: Ars Nova DC',
 'Ajin Part 2: Shoutotsu',
 'Akame ga Kill! Theater',
 'Di Gi Charat: Hoshi no Tabi',
 'Medaka no Gakkou',
 'Tonari no Tokoro',
 'Kamikaze Kaitou Jeanne',
 'Precure All Stars Movie DX3: Mirai ni Todoke! Sekai wo Tsunagu☆Nijiiro no Hana',
 'Chirin no Suzu',
 'Ouritsu Uchuugun: Honneamise no Tsubasa',
 'Mnemosyne: Mnemosyne no Musume-tachi',
 'Sangokushi',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa',
 'Slayers: The Motion Picture',
 'World Destruction: Sekai Bokumetsu no Rokunin',
 'Love Live! School Idol Project: μ&#039;s →NEXT LoveLive! 2014 - Endless Parade Makuai Drama',
 'Moyashimon: Kin Gekijou Deluxe',
 'Senjou no Valkyria: SenVal Theater',
 'Monkey King: Hero Is Back',
 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season',
 'Irregular Hunter X: The Day of Sigma',
 'Shakugan no Shana II (Second)',
 'One Piece: Nenmatsu Tokubetsu Kikaku! Mugiwara no Luffy Oyabun Torimonochou',
 'Muku Hatojuu no Meiken Monogatari',
 'Dead Leaves',
 'Hells',
 'Popee the Performer',
 'Trigun',
 'Black Jack (TV): Hizouban Specials',
 'Doraemon Movie 34: Shin Nobita no Daimakyou - Peko to 5-nin no Tankentai',
 'Sweat Punch',
 'Lupin III: Sweet Lost Night - Mahou no Lamp wa Akumu no Yokan',
 'Isekai no Seikishi Monogatari',
 'Hakkenden: Touhou Hakken Ibun',
 'Noragami',
 'Tenchi Muyou! Ryououki 4th Season',
 'Digimon Adventure Movie',
 'Utawarerumono',
 'Break Blade 3: Kyoujin no Ato',
 'Kaitou Joker 3rd Season',
 'Majime ni Fumajime Kaiketsu Zorori',
 '1000-nen Joou: Queen Millennia',
 'Kyouryuu Boukenki Jura Tripper',
 'Jikuu Boukenki Zentrix',
 'Tenjou Tenge: The Past Chapter',
 'Arslan Senki (TV) OVA',
 'Ansatsu Kyoushitsu (TV) 2nd Season: Kagaijugyou-hen',
 'Rurouni Kenshin Special',
 'Mardock Scramble: The First Compression',
 'Berserk',
 'Michitekuru Toki no Mukou ni',
 'JoJo no Kimyou na Bouken: Adventure',
 'Doraemon Movie 11: Nobita to Animal Planet',
 'Naruto: Shippuuden',
 'City Hunter &#039;91',
 'Mermaid Melody Pichi Pichi Pitch',
 'Doraemon Movie 29: Shin Nobita no Uchuu Kaitakushi',
 'Strike the Blood II',
 'Hakuouki Hekketsuroku',
 'Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation',
 'Neon Genesis Evangelion',
 'Hakuouki Sekkaroku',
 'Mahou Shoujo Lyrical Nanoha A&#039;s',
 'Initial D Fifth Stage',
 'Hokuto no Ken: Toki-den',
 'Fate/stay night Movie: Unlimited Blade Works',
 'Deadman Wonderland',
 'Naruto: Shippuuden Movie 2 - Kizuna',
 'Ajin Part 1: Shoudou',
 'Evangelion: 3.0 You Can (Not) Redo',
 'Slayers Great',
 'Boku no Hero Academia',
 'Yume de Aetara (TV)',
 'Rurouni Kenshin: Meiji Kenkaku Romantan',
 'Yu☆Gi☆Oh! Arc-V',
 'Usavich II',
 'Scrapped Princess',
 'Di Gi Charat Ohanami Special',
 'Sword Art Online: Sword Art Offline - Extra Edition',
 'Anime Koukyoushi: Jungle Taitei',
 'Owari no Seraph',
 'Pokemon 3D Adventure 2: Pikachu no Kaitei Daibouken',
 'Heavy Object',
 'Nurarihyon no Mago',
 'YAT Anshin! Uchuu Ryokou 2',
 'Chrno Crusade',
 'Final Fantasy VII: Advent Children',
 'Negima!?',
 'KanColle Movie',
 'Magic Knight Rayearth',
 'Sword Art Online II: Sword Art Offline II',
 'Jam the Housnail',
 'Shika to Kanta',
 'Fate/stay night',
 'Durarara!!x2 Ten: Onoroke Chakapoko',
 'Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa',
 'Hakuouki Reimeiroku Tokuten Disc',
 'Detective Conan OVA 03: Conan and Heiji and the Vanished Boy',
 'Hellsing I: Digest for Freaks',
 'Initial D Second Stage',
 'Dokidoki Densetsu: Mahoujin Guru Guru',
 'Slayers Return',
 'Transformers Victory',
 'Shimajirou to Ehon no Kuni',
 'Black Jack 21',
 'God Eater',
 'Yu☆Gi☆Oh! 5D&#039;s',
 'Slayers Gorgeous',
 'Sennen Joyuu',
 'Chikyuu Shoujo Arjuna',
 'Dragon Ball Z Movie 07: Kyokugen Battle!! Sandai Super Saiyajin',
 'Kyousou Giga (TV)',
 'Tokyo Ghoul: &quot;Jack&quot;',
 'Katekyo Hitman Reborn!',
 'Karas',
 'Magi: The Labyrinth of Magic',
 'Noragami Aragoto OVA',
 'Tenjou Tenge: The Ultimate Fight',
 'Fight Ippatsu! Juuden-chan!! Specials',
 'Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen',
 'Teach',
 'Baccano!',
 'Street Fighter II V',
 'Love Hina Haru Special: Kimi Sakura Chiru Nakare!!',
 'Inferno Cop',
 'Break Blade 4: Sanka no Chi',
 'Shakugan no Shana',
 'Tetsuwan Birdy Decode:02',
 'Seimei no Kagaku: Micro Patrol',
 'Dragon Ball: Super Saiya-jin Zetsumetsu Keikaku',
 'One Punch Man Specials',
 'Black Clover',
 'Code Geass: Hangyaku no Lelouch Special Edition Black Rebellion',
 'Star Driver: Kagayaki no Takuto',
 'Final Approach',
 'Rokudenashi Blues',
 'Shadow Skill: Eigi',
 'Pandane to Tamago-hime',
 'Erementar Gerad',
 'Shakugan no Shana III (Final)',
 'Magi: Sinbad no Bouken (TV)',
 'Panyo Panyo Di Gi Charat',
 'Seirei no Moribito',
 'Yousei Florence',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'One Punch Man: Road to Hero',
 'Toaru Majutsu no Index II',
 'Sengoku Basara Two: Ryuko, Itadaki no Chikai! Atsuki Mirai e Kakeru Tamashii!!',
 'Kill la Kill Special',
 'Fushigi Yuugi: Eikouden',
 'Mobile Suit Gundam 00 Second Season',
 'Ganbare Swimmy',
 'JoJo no Kimyou na Bouken: Stardust Crusaders',
 'Tekkon Kinkreet',
 'Btooom!',
 'Fractale',
 'Sanzoku no Musume Ronja',
 'Doraemon Movie 07: Nobita to Tetsujin Heidan',
 'Higashi no Eden',
 'Super Robot Taisen OG: The Inspector',
 'Mahou Shoujo Lyrical Nanoha: The Movie 1st',
 'Pygmalio',
 'Ou Dorobou Jing in Seventh Heaven',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
 'Baby Baachan',
 'Mirai Shounen Conan (Movie)',
 'Kuroshitsuji',
 'Gad Guard',
 'Yuusha-Ou GaoGaiGar Final Grand Glorious Gathering',
 'Hayate no Gotoku!!',
 'FLCL',
 'Dae Jang Geum: Jang Geum&#039;s Dream 2',
 '.hack//Sign',
 'Kuromukuro',
 'Fate/Zero: Onegai! Einzbern Soudanshitsu',
 'Tales of Gekijou',
 'Shikabane Hime: Kuro',
 'Kiddy Grade: Truth Dawn',
 'Gintama Movie: Shinyaku Benizakura-hen',
 'Anime 80-nichikan Sekai Isshuu',
 'One Piece Film: Strong World',
 'Doraemon Movie 33: Nobita no Himitsu Dougu Museum',
 'Yume no Crayon Oukoku',
 'Geunyeoneun Yeppeotda',
 'Akira',
 'Nanatsu no Umi no Tico Specials',
 'Spriggan',
 'Sei Juushi Bismarck',
 'Beet the Vandel Buster',
 'El Hazard: The Magnificent World',
 'Beelzebub',
 'Phantom: Requiem for the Phantom',
 'Gintama: Yorinuki Gintama-san on Theater 2D',
 'Deltora Quest',
 'Mobile Suit Gundam 00',
 'Akatsuki no Yona OVA',
 'Shingeki no Kyojin Movie 1: Guren no Yumiya',
 'Happy☆Lucky Bikkuriman',
 'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture',
 'Great Mazinger',
 'Sidonia no Kishi Movie',
 'Final Fantasy VII: Advent Children - Venice Film Festival Footage',
 'Mai-HiME: Kuro no Mai/Saigo no Bansan',
 'Ichigo Ichie: Kimi no Kotoba',
 'Midnight Horror School',
 'Noramimi',
 'Metal Fight Beyblade 4D',
 'Angel Beats! Specials',
 'Imawa no Kuni no Alice (OVA)',
 'Kiddy Grade: Maelstrom',
 'Elsword: El Lady',
 'Break Blade 6: Doukoku no Toride',
 'Durarara!!x2 Ketsu: Dufufufu!!',
 'Gift: Eternal Rainbow',
 'Senjou no Valkyria',
 'NG Knight Ramune &amp; 40',
 'Kara no Kyoukai 3: Tsuukaku Zanryuu',
 'One Piece Film: Z',
 'Groove Adventure Rave',
 'Biohazard: Damnation',
 'Mirai Nikki Redial',
 'Guilty Crown Kiseki: Reassortment',
 'Mazinkaiser: Shitou! Ankoku Dai Shogun',
 'Towa no Quon 3: Mugen no Renza',
 'Slayers Special',
 'Slayers Evolution-R',
 'Juuni Kokuki',
 'Doraemon',
 'InuYasha: Guren no Houraijima',
 'Buddy Complex: Kanketsu-hen - Ano Sora ni Kaeru Mirai de',
 'Mobile Suit Gundam 00: Tenshitachi no Kiseki',
 'Akazukin Chacha',
 'Tenchi Muyou! Ryououki',
 'Mirai Shounen Conan: Tokubetsu-hen - Kyodaiki Gigant no Fukkatsu',
 'The Last: Naruto the Movie',
 'Hokuto no Ken 2',
 'Gensoumaden Saiyuuki: Kibou no Zaika',
 'Muumin',
 'Jormungand: Perfect Order',
 'Kara no Kyoukai Remix: Gate of Seventh Heaven',
 'Innocent Venus',
 'Elf wo Karu Mono-tachi II',
 'Tsuyoshi Shikkari Shinasai: Tsuyoshi no Time Machine de Shikkari Shinasai',
 'Dragon Ball Z',
 'Tsubasa: Shunraiki',
 'Elf wo Karu Mono-tachi',
 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen',
 'Macross F: Close Encounter - Deculture Edition',
 'Kakumeiki Valvrave',
 'Gongitsune',
 'Top wo Nerae 2! Diebuster',
 'One Piece Movie 7: Karakuri-jou no Mecha Kyohei',
 'Bleach Movie 4: Jigoku-hen',
 'Detective Conan OVA 05: The Target is Kogoro! The Detective Boys&#039; Secret Investigation',
 'InuYasha: Kanketsu-hen',
 'Vandread: The Second Stage',
 'High School Fleet',
 'Line Offline: Salaryman',
 'Shigofumi Picture Drama',
 'Nyani ga Nyandaa Nyandaa Kamen',
 'Code Geass: Boukoku no Akito 2 - Hikisakareshi Yokuryuu',
 'Top wo Nerae! Gunbuster',
 'Detective Conan OVA 01: Conan vs. Kid vs. Yaiba',
 'Kinnikuman',
 'Peter Pan no Bouken',
 'Mashin Eiyuuden Wataru 2',
 'Detective Conan Movie 19: The Hellfire Sunflowers',
 'Yoroiden Samurai Troopers Gaiden',
 'El Hazard: The Wanderers',
 'Black★Rock Shooter',
 'Full Metal Panic!',
 'Heartcatch Precure!',
 'Mahoujin Guru Guru Movie',
 'Hakuouki OVA',
 'Shakugan no Shana Movie',
 'Fullmetal Alchemist: Brotherhood',
 'Fushigi no Umi no Nadia Specials',
 'Naruto',
 'Kaze no Stigma',
 'Detective Conan OVA 07: A Challenge from Agasa! Agasa vs. Conan and the Detective Boys',
 'Noblesse: Awakening',
 'Giniro no Kami no Agito',
 'Naruto Movie 1: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo!',
 'Jungle Taitei: Susume Leo!',
 'Omae Umasou da na',
 'Shounen Onmyouji',
 'Log Horizon',
 'Sakura Taisen',
 'Sakura Taisen: Gouka Kenran',
 'Shin Koihime†Musou: Otome Tairan',
 'Sangokushi II: Amakakeru Otoko-tachi',
 'Captain Harlock',
 'Jungle Book Shounen Mowgli',
 'Manga Sekai Mukashibanashi',
 'Nils no Fushigi na Tabi',
 'RD Sennou Chousashitsu',
 'Fullmetal Alchemist',
 'Macross Δ',
 'Dragon Ball Z Movie 06: Gekitotsu!! 100-oku Power no Senshi-tachi',
 'Pokemon Fushigi no Dungeon: Sora no Tankentai - Toki to Yami wo Meguru Saigo no Bouken',
 'One Piece Film: Gold',
 'Ginga Nagareboshi Gin',
 'Initial D Third Stage',
 'Oyayubi Hime Monogatari',
 'Shin Captain Tsubasa',
 'New Prince of Tennis OVA vs. Genius10',
 'Hakuouki Reimeiroku',
 'World Trigger',
 'Dance in the Vampire Bund',
 'Mobile Suit Gundam',
 'One Piece: Mamore! Saigo no Dai Butai',
 'Bungou Stray Dogs',
 'Mob Psycho 100',
 'Tokyo Ghoul: &quot;Pinto&quot;',
 'Mai-Otome Zwei',
 'Bounen no Xamdou',
 'D.Gray-man',
 'Mai Mai Shinko to Sennen no Mahou',

In [70]:
recommend_anime(1, 0.95)

['Doraemon Movie 20: Nobita no Uchuu Hyouryuuki',
 'Doraemon Movie 01: Nobita no Kyouryuu',
 'Daisetsusan no Yuusha Kibaou',
 'Hyakko OVA',
 'Mobile Suit Gundam Thunderbolt: December Sky',
 'Eyeshield 21',
 'GR: Giant Robo',
 'Trigun: Badlands Rumble',
 'Mutsu Enmei Ryuu Gaiden: Shura no Toki',
 'Wellber no Monogatari: Sisters of Wellber Zwei',
 'JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season',
 'D.Gray-man Hallow',
 'Hunter x Hunter OVA',
 'Hunter x Hunter: Greed Island Final',
 'Hellsing',
 'Gundam Build Fighters Try',
 'Dae Jang Geum: Jang Geum&#039;s Dream',
 'Tiger &amp; Bunny',
 'Owari no Seraph: Nagoya Kessen-hen',
 'Gintama: Jump Festa 2014 Special',
 'Chiisana Ahiru no Ooki na Ai no Monogatari: Ahiru no Kwak',
 'Mobile Suit Gundam Seed',
 'Persona 3 the Movie 3: Falling Down',
 'Negibouzu no Asatarou',
 'City Hunter 2',
 'Ramayana: The Legend of Prince Rama',
 'Tales of Phantasia The Animation',
 'Prince of Tennis: The National Tournament',
 'Code Geass: Boukoku no Akito 3 - Kagayaku Mono Ten yori Otsu',
 'Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s',
 'Kyoukaisenjou no Horizon II',
 'Lupin III: The Last Job',
 'Kekkai Sensen',
 'Seikai no Senki Special',
 'Prince of Tennis: The National Tournament Semifinals',
 'Mahou Sensei Negima! Anime Final',
 'Hakuouki Movie 1: Kyoto Ranbu',
 'The Big O',
 'Dirty Pair: The Movie',
 'Hulu Xiongdi',
 'Mobile Suit Gundam Wing: Endless Waltz Movie',
 'Digimon Tamers: Bousou Digimon Tokkyuu',
 'Durarara!! Specials',
 'Mirai Shounen Conan 2: Taiga Daibouken',
 'Chikyuu Bouei Kigyou Dai-Guard',
 'Musekinin Kanchou Tylor OVA',
 'Katanagatari',
 'Meiken Lassie',
 'Astarotte no Omocha!',
 'Doraemon Movie 13: Nobita to Kumo no Oukoku',
 'Tengen Toppa Gurren Lagann',
 'Shakugan no Shana Movie Special',
 'The Legend of Huainanzi 2nd Season',
 'Kino no Tabi: The Beautiful World',
 'Kagee Aesop Monogatari',
 '91 Days',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen',
 'Bishoujo Senshi Sailor Moon: Sailor Stars - Hero Club',
 'Vampire Hunter D (2000)',
 'Uchuu no Stellvia',
 'Mardock Scramble: The Second Combustion',
 'Doraemon Movie 08: Nobita to Ryuu no Kishi',
 'Doraemon Movie 36: Shin Nobita no Nippon Tanjou',
 'Dragon Ball Z Movie 05: Tobikkiri no Saikyou tai Saikyou',
 'Fullmetal Alchemist: Reflections',
 'Ayashi no Ceres',
 'Kemono no Souja Erin: Soushuuhen',
 'Di Gi Charat Natsuyasumi Special',
 'Phantom: Requiem for the Phantom Picture Drama',
 'Otanoshimi Anime Gekijou',
 'Dorimogu Daa!!',
 'Speed Grapher',
 'Code Geass: Boukoku no Akito 4 - Nikushimi no Kioku Kara',
 'Angel Beats!',
 'Ajin OVA',
 'Uchuu Senkan Yamato 2199: Hoshimeguru Hakobune',
 'Tsukuyomi: Moon Phase Special',
 'Magi: The Kingdom of Magic',
 'Mushrambo',
 'Hunter x Hunter',
 'Minami no Niji no Lucy',
 'Noragami Aragoto',
 'Dogs: Bullets &amp; Carnage',
 'Captain Tsubasa: Road to 2002',
 'Canaan',
 'Di Gi Charat Christmas Special',
 'Fumiko no Kokuhaku',
 'Hentai Ouji to Warawanai Neko.: Henneko BBS',
 'Inazuma Eleven Go: TCG CM NG-shuu',
 'Yuu☆Yuu☆Hakusho: Mu Mu Hakusho',
 'Bonobono',
 'Mak Dau Xiang Dang Dang',
 'Tengen Toppa Gurren Lagann Movie: Gurren-hen',
 'Trinity Blood',
 'Guilty Crown',
 'Mobile Suit Gundam Wing',
 'Mobile Suit Gundam Wing: Endless Waltz',
 'Soukou Kihei Votoms',
 'Break Blade 1: Kakusei no Toki',
 'Prince of Tennis',
 'Witchblade',
 'Gregory Horror Show: The Last Train',
 'The Rose and Women of Versailles',
 'Donten ni Warau',
 'Gintama: Jump Festa 2015 Special',
 'Kiteretsu Daihyakka',
 'Saiunkoku Monogatari Soushuuhen',
 'Pokemon 3D Adventure: Mew wo Sagase!',
 'Redline',
 'Kachou Ouji',
 'Druaga no Tou: The Aegis of Uruk',
 'Gintama: Dai Hanseikai',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Mermaid Melody Pichi Pichi Pitch Pure',
 'Otogizoushi',
 'Kubikiri Cycle: Aoiro Savant to Zaregototsukai',
 'Yuu☆Yuu☆Hakusho',
 'Rakudai Kishi no Cavalry',
 'Senki Zesshou Symphogear G: In the Distance, That Day, When the Star Became Music...',
 'Senki Zesshou Symphogear GX: Believe in Justice and Hold a Determination to Fist.',
 'Aoi Blink',
 'Mo Jing Lieren 2nd Season',
 'Shen Ming Zhi Zhou',
 'Yong Zhe Da Mao Xian 2nd Season',
 'Daisougen no Chiisana Tenshi: Bush Baby',
 'Hokuto no Ken',
 'Towa no Quon 2: Konton no Ranbu',
 'Baccano! Specials',
 'Slayers Excellent',
 'Hakuouki Movie 2: Shikon Soukyuu',
 'C: The Money of Soul and Possibility Control',
 'Mahoutsukai Precure! Movie',
 'Shijou Saikyou no Deshi Kenichi',
 'Mazinkaiser SKL',
 'Stranger: Mukou Hadan',
 'Sengoku Basara Two',
 'Pokemon XY: Sora no Hahen',
 'JoJo no Kimyou na Bouken (TV)',
 'Doraemon Movie 10: Nobita no Nippon Tanjou',
 'Doraemon Movie 23: Nobita to Robot Kingdom',
 'Hunter x Hunter: Greed Island',
 'Asura Cryin&#039; 2',
 'Mahou Senshi Louie',
 'Rakuen Tsuihou: Expelled from Paradise',
 'Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi',
 'Digimon Adventure 02: Diablomon no Gyakushuu',
 'Lupin III vs. Detective Conan: The Movie',
 'Doraemon Movie 02: Nobita no Uchuu Kaitakushi',
 'Prince of Tennis: The Two Samurai, The First Game',
 'Slayers Premium',
 'Black Bullet',
 'Doraemon Movie 19: Nobita no Nankai Daibouken',
 'Working&#039;!! Announcement Specials',
 'Captain Tsubasa J',
 'Pokemon Black and White 2: Introduction Movie',
 'Fushigi Yuugi OVA',
 'Gintama: Shinyaku Benizakura-hen',
 'Solty Rei',
 'Mobile Suit Gundam Thunderbolt',
 'Dirty Pair',
 'Mahou Shoujo-tai Arusu',
 'Doraemon Movie 30: Nobita no Ningyo Daikaisen',
 'Doraemon Movie 32: Nobita to Kiseki no Shima - Animal Adventure',
 'Medarot',
 'Slayers Revolution',
 'Chuuzumou',
 'Di Gi Charat Tsuyu Specials',
 'Madan no Ou to Vanadis: Tigre-kun to Vanadi-chu',
 'Jungle Kurobee',
 'Only You: Viva! Cabaret Club',
 'Shingeki no Kyojin OVA',
 'Elfen Lied',
 'Ansatsu Kyoushitsu (TV)',
 'Shukufuku no Campanella: La Campanella Della Benedizione',
 'Cross Ange: Tenshi to Ryuu no Rondo',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2',
 'Pokemon: Mizu no Miyako no Mamorigami Latias to Latios',
 'Ie Naki Ko Remi Specials (2001)',
 'Redline Pilot',
 'Full Metal Panic? Fumoffu',
 'Texhnolyze',
 'Sobakasu Pucchi',
 'Toaru Majutsu no Index',
 'Hakkenden: Touhou Hakken Ibun 2nd Season',
 'Sengoku Basara Movie: The Last Party',
 'Dirty Pair OVA',
 'Zegapain',
 'Coo: Tooi Umi kara Kita Coo',
 'Saint Seiya: Meiou Hades Elysion-hen',
 'Hatenkou Yuugi',
 'Persona 3 the Movie 1: Spring of Birth',
 'Tiger &amp; Bunny Movie 2: The Rising',
 'Gungrave',
 'Astarotte no Omocha! EX',
 'Captain Tsubasa',
 'Ao no Exorcist',
 'Accel World',
 'Kikou Senki Dragonar',
 'Doraemon Movie 16: Nobita no Sousei Nikki',
 'Dan Doh!!',
 'Code Geass: Boukoku no Akito 1 - Yokuryuu wa Maiorita',
 'Manie-Manie: Meikyuu Monogatari',
 'Bleach',
 'Shiawase Sou no Okojo-san',
 'Blue Gender',
 'Heroic Age',
 'Tokyo Ghoul',
 'Toaru Majutsu no Index: Endymion no Kiseki',
 'City Hunter',
 'Tibet Inu Monogatari',
 'Boruto: Naruto the Movie',
 'Break Blade 2: Ketsubetsu no Michi',
 'Kazemakase Tsukikage Ran',
 'Kill la Kill',
 'Chou Denji Robo Combattler V',
 'Ginga Kikoutai Majestic Prince',
 'Kara no Kyoukai 6: Boukyaku Rokuon',
 'Yuki no Joou',
 'Gintama: Shiroyasha Koutan',
 'Pokemon: Maboroshi no Pokemon Lugia Bakutan',
 'Kakumeiki Valvrave 2nd Season',
 'Initial D Fourth Stage',
 'Mardock Scramble: The Third Exhaust',
 'Kaitou Joker 2nd Season',
 'Nanatsu no Taizai',
 'Nurarihyon no Mago: Sennen Makyou',
 'Doraemon Movie 12: Nobita no Dorabian Nights',
 'Kaitou Joker 4th Season',
 'Ketsuekigata-kun!',
 'Doushitemo Eto ni Hairitai',
 'Mirai Nikki',
 'YAT Anshin! Uchuu Ryokou',
 'Seikai no Monshou Special',
 'Shijou Saikyou no Deshi Kenichi OVA',
 'Strike Witches Movie',
 'Kenran Butou Sai: The Mars Daybreak',
 'Mononoke Hime',
 'Appleseed Saga Ex Machina',
 'Kumo no You ni Kaze no You ni',
 'Initial D First Stage',
 'Ou Dorobou Jing',
 'Dimension W',
 'Tamala 2010: A Punk Cat in Space',
 'Cencoroll',
 'Nurarihyon no Mago OVA',
 'Aoki Hagane no Arpeggio: Ars Nova',
 'Sengoku Basara',
 'Doraemon Movie 03: Nobita no Daimakyou',
 'Cosmic Baton Girl Comet-san',
 'Brigadoon: Marin to Melan',
 'Wagamama☆Fairy Mirumo de Pon!',
 'Long Zai Na Li',
 'Dragon League',
 'Kokoro Toshokan',
 'Pokemon the Movie XY&amp;Z: Volcanion to Karakuri no Magiana',
 'Mobile Suit Gundam Seed Special Edition',
 'Digimon Tamers: Boukensha-tachi no Tatakai',
 'Tytania',
 'Blood+',
 'Ao no Exorcist Movie',
 'Tsubasa: Tokyo Revelations',
 'Ajin',
 'Senki Zesshou Symphogear G: In the Distance, That Day, When the Star Became Music... Specials',
 'Toaru Kagaku no Railgun S: Daiji na Koto wa Zenbu Sentou ni Osowatta',
 'Hyakujuu-Ou GoLion',
 'Ghost in the Shell (2015)',
 'Transformers: Choujin Master Force',
 'Mobile Suit Gundam 00 Special Edition',
 'Tom Sawyer no Bouken',
 'Pokemon the Movie XY: Ring no Choumajin Hoopa',
 '.hack//Roots',
 'Aldnoah.Zero',
 'JoJo no Kimyou na Bouken: Diamond wa Kudakenai',
 'Marco: Haha wo Tazunete Sanzenri',
 'Zetsuen no Tempest',
 'Psycho-Pass 2',
 'One Piece',
 'Towa no Quon 1: Utakata no Kaben',
 'Tatsu no Ko Tarou',
 'City Hunter 3',
 'Escaflowne',
 'Samurai Champloo',
 'Moetan',
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Dragon Ball Z Movie 09: Ginga Girigiri!! Bucchigiri no Sugoi Yatsu',
 'Terra e... (TV)',
 'Darker than Black: Ryuusei no Gemini',
 'Mobile Suit Gundam 00 The Movie: A Wakening of the Trailblazer',
 'Sora wo Kakeru Shoujo',
 'Grappler Baki: Saidai Tournament-hen',
 'Mashin Eiyuuden Wataru',
 'Kyoro-chan',
 'Seton Doubutsuki',
 'One Piece: Kinkyuu Kikaku One Piece Kanzen Kouryakuhou',
 'Toaru Kagaku no Railgun: Misaka-san wa Ima Chuumoku no Mato desukara',
 'Persona 3 the Movie 2: Midsummer Knight&#039;s Dream',
 'Doraemon Movie 24: Nobita to Fushigi Kaze Tsukai',
 'Aoki Hagane no Arpeggio: Ars Nova DC',
 'Ajin Part 2: Shoutotsu',
 'Akame ga Kill! Theater',
 'Di Gi Charat: Hoshi no Tabi',
 'Medaka no Gakkou',
 'Tonari no Tokoro',
 'Kamikaze Kaitou Jeanne',
 'Precure All Stars Movie DX3: Mirai ni Todoke! Sekai wo Tsunagu☆Nijiiro no Hana',
 'Chirin no Suzu',
 'Ouritsu Uchuugun: Honneamise no Tsubasa',
 'Mnemosyne: Mnemosyne no Musume-tachi',
 'Sangokushi',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa',
 'Slayers: The Motion Picture',
 'World Destruction: Sekai Bokumetsu no Rokunin',
 'Love Live! School Idol Project: μ&#039;s →NEXT LoveLive! 2014 - Endless Parade Makuai Drama',
 'Moyashimon: Kin Gekijou Deluxe',
 'Senjou no Valkyria: SenVal Theater',
 'Monkey King: Hero Is Back',
 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season',
 'Irregular Hunter X: The Day of Sigma',
 'Shakugan no Shana II (Second)',
 'One Piece: Nenmatsu Tokubetsu Kikaku! Mugiwara no Luffy Oyabun Torimonochou',
 'Muku Hatojuu no Meiken Monogatari',
 'Dead Leaves',
 'Hells',
 'Popee the Performer',
 'Trigun',
 'Black Jack (TV): Hizouban Specials',
 'Doraemon Movie 34: Shin Nobita no Daimakyou - Peko to 5-nin no Tankentai',
 'Sweat Punch',
 'Lupin III: Sweet Lost Night - Mahou no Lamp wa Akumu no Yokan',
 'Isekai no Seikishi Monogatari',
 'Hakkenden: Touhou Hakken Ibun',
 'Noragami',
 'Tenchi Muyou! Ryououki 4th Season',
 'Digimon Adventure Movie',
 'Utawarerumono',
 'Break Blade 3: Kyoujin no Ato',
 'Kaitou Joker 3rd Season',
 'Majime ni Fumajime Kaiketsu Zorori',
 '1000-nen Joou: Queen Millennia',
 'Kyouryuu Boukenki Jura Tripper',
 'Jikuu Boukenki Zentrix',
 'Tenjou Tenge: The Past Chapter',
 'Arslan Senki (TV) OVA',
 'Ansatsu Kyoushitsu (TV) 2nd Season: Kagaijugyou-hen',
 'Rurouni Kenshin Special',
 'Mardock Scramble: The First Compression',
 'Berserk',
 'Michitekuru Toki no Mukou ni',
 'JoJo no Kimyou na Bouken: Adventure',
 'Doraemon Movie 11: Nobita to Animal Planet',
 'Naruto: Shippuuden',
 'City Hunter &#039;91',
 'Mermaid Melody Pichi Pichi Pitch',
 'Doraemon Movie 29: Shin Nobita no Uchuu Kaitakushi',
 'Strike the Blood II',
 'Hakuouki Hekketsuroku',
 'Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation',
 'Neon Genesis Evangelion',
 'Hakuouki Sekkaroku',
 'Mahou Shoujo Lyrical Nanoha A&#039;s',
 'Initial D Fifth Stage',
 'Hokuto no Ken: Toki-den',
 'Fate/stay night Movie: Unlimited Blade Works',
 'Deadman Wonderland',
 'Naruto: Shippuuden Movie 2 - Kizuna',
 'Ajin Part 1: Shoudou',
 'Evangelion: 3.0 You Can (Not) Redo',
 'Slayers Great',
 'Boku no Hero Academia',
 'Yume de Aetara (TV)',
 'Rurouni Kenshin: Meiji Kenkaku Romantan',
 'Yu☆Gi☆Oh! Arc-V',
 'Usavich II',
 'Scrapped Princess',
 'Di Gi Charat Ohanami Special',
 'Sword Art Online: Sword Art Offline - Extra Edition',
 'Anime Koukyoushi: Jungle Taitei',
 'Owari no Seraph',
 'Pokemon 3D Adventure 2: Pikachu no Kaitei Daibouken',
 'Heavy Object',
 'Nurarihyon no Mago',
 'YAT Anshin! Uchuu Ryokou 2',
 'Chrno Crusade',
 'Final Fantasy VII: Advent Children',
 'Negima!?',
 'KanColle Movie',
 'Magic Knight Rayearth',
 'Sword Art Online II: Sword Art Offline II',
 'Jam the Housnail',
 'Shika to Kanta',
 'Fate/stay night',
 'Durarara!!x2 Ten: Onoroke Chakapoko',
 'Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa',
 'Hakuouki Reimeiroku Tokuten Disc',
 'Detective Conan OVA 03: Conan and Heiji and the Vanished Boy',
 'Hellsing I: Digest for Freaks',
 'Initial D Second Stage',
 'Dokidoki Densetsu: Mahoujin Guru Guru',
 'Slayers Return',
 'Transformers Victory',
 'Shimajirou to Ehon no Kuni',
 'Black Jack 21',
 'God Eater',
 'Yu☆Gi☆Oh! 5D&#039;s',
 'Slayers Gorgeous',
 'Sennen Joyuu',
 'Chikyuu Shoujo Arjuna',
 'Dragon Ball Z Movie 07: Kyokugen Battle!! Sandai Super Saiyajin',
 'Kyousou Giga (TV)',
 'Tokyo Ghoul: &quot;Jack&quot;',
 'Katekyo Hitman Reborn!',
 'Karas',
 'Magi: The Labyrinth of Magic',
 'Noragami Aragoto OVA',
 'Tenjou Tenge: The Ultimate Fight',
 'Fight Ippatsu! Juuden-chan!! Specials',
 'Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen',
 'Teach',
 'Baccano!',
 'Street Fighter II V',
 'Love Hina Haru Special: Kimi Sakura Chiru Nakare!!',
 'Inferno Cop',
 'Break Blade 4: Sanka no Chi',
 'Shakugan no Shana',
 'Tetsuwan Birdy Decode:02',
 'Seimei no Kagaku: Micro Patrol',
 'Dragon Ball: Super Saiya-jin Zetsumetsu Keikaku',
 'One Punch Man Specials',
 'Black Clover',
 'Code Geass: Hangyaku no Lelouch Special Edition Black Rebellion',
 'Star Driver: Kagayaki no Takuto',
 'Final Approach',
 'Rokudenashi Blues',
 'Shadow Skill: Eigi',
 'Pandane to Tamago-hime',
 'Erementar Gerad',
 'Shakugan no Shana III (Final)',
 'Magi: Sinbad no Bouken (TV)',
 'Panyo Panyo Di Gi Charat',
 'Seirei no Moribito',
 'Yousei Florence',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'One Punch Man: Road to Hero',
 'Toaru Majutsu no Index II',
 'Sengoku Basara Two: Ryuko, Itadaki no Chikai! Atsuki Mirai e Kakeru Tamashii!!',
 'Kill la Kill Special',
 'Fushigi Yuugi: Eikouden',
 'Mobile Suit Gundam 00 Second Season',
 'Ganbare Swimmy',
 'JoJo no Kimyou na Bouken: Stardust Crusaders',
 'Tekkon Kinkreet',
 'Btooom!',
 'Fractale',
 'Sanzoku no Musume Ronja',
 'Doraemon Movie 07: Nobita to Tetsujin Heidan',
 'Higashi no Eden',
 'Super Robot Taisen OG: The Inspector',
 'Mahou Shoujo Lyrical Nanoha: The Movie 1st',
 'Pygmalio',
 'Ou Dorobou Jing in Seventh Heaven',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
 'Baby Baachan',
 'Mirai Shounen Conan (Movie)',
 'Kuroshitsuji',
 'Gad Guard',
 'Yuusha-Ou GaoGaiGar Final Grand Glorious Gathering',
 'Hayate no Gotoku!!',
 'FLCL',
 'Dae Jang Geum: Jang Geum&#039;s Dream 2',
 '.hack//Sign',
 'Kuromukuro',
 'Fate/Zero: Onegai! Einzbern Soudanshitsu',
 'Tales of Gekijou',
 'Shikabane Hime: Kuro',
 'Kiddy Grade: Truth Dawn',
 'Gintama Movie: Shinyaku Benizakura-hen',
 'Anime 80-nichikan Sekai Isshuu',
 'One Piece Film: Strong World',
 'Doraemon Movie 33: Nobita no Himitsu Dougu Museum',
 'Yume no Crayon Oukoku',
 'Geunyeoneun Yeppeotda',
 'Akira',
 'Nanatsu no Umi no Tico Specials',
 'Spriggan',
 'Sei Juushi Bismarck',
 'Beet the Vandel Buster',
 'El Hazard: The Magnificent World',
 'Beelzebub',
 'Phantom: Requiem for the Phantom',
 'Gintama: Yorinuki Gintama-san on Theater 2D',
 'Deltora Quest',
 'Mobile Suit Gundam 00',
 'Akatsuki no Yona OVA',
 'Shingeki no Kyojin Movie 1: Guren no Yumiya',
 'Happy☆Lucky Bikkuriman',
 'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture',
 'Great Mazinger',
 'Sidonia no Kishi Movie',
 'Final Fantasy VII: Advent Children - Venice Film Festival Footage',
 'Mai-HiME: Kuro no Mai/Saigo no Bansan',
 'Ichigo Ichie: Kimi no Kotoba',
 'Midnight Horror School',
 'Noramimi',
 'Metal Fight Beyblade 4D',
 'Angel Beats! Specials',
 'Imawa no Kuni no Alice (OVA)',
 'Kiddy Grade: Maelstrom',
 'Elsword: El Lady',
 'Break Blade 6: Doukoku no Toride',
 'Durarara!!x2 Ketsu: Dufufufu!!',
 'Gift: Eternal Rainbow',
 'Senjou no Valkyria',
 'NG Knight Ramune &amp; 40',
 'Kara no Kyoukai 3: Tsuukaku Zanryuu',
 'One Piece Film: Z',
 'Groove Adventure Rave',
 'Biohazard: Damnation',
 'Mirai Nikki Redial',
 'Guilty Crown Kiseki: Reassortment',
 'Mazinkaiser: Shitou! Ankoku Dai Shogun',
 'Towa no Quon 3: Mugen no Renza',
 'Slayers Special',
 'Slayers Evolution-R',
 'Juuni Kokuki',
 'Doraemon',
 'InuYasha: Guren no Houraijima',
 'Buddy Complex: Kanketsu-hen - Ano Sora ni Kaeru Mirai de',
 'Mobile Suit Gundam 00: Tenshitachi no Kiseki',
 'Akazukin Chacha',
 'Tenchi Muyou! Ryououki',
 'Mirai Shounen Conan: Tokubetsu-hen - Kyodaiki Gigant no Fukkatsu',
 'The Last: Naruto the Movie',
 'Hokuto no Ken 2',
 'Gensoumaden Saiyuuki: Kibou no Zaika',
 'Muumin',
 'Jormungand: Perfect Order',
 'Kara no Kyoukai Remix: Gate of Seventh Heaven',
 'Innocent Venus',
 'Elf wo Karu Mono-tachi II',
 'Tsuyoshi Shikkari Shinasai: Tsuyoshi no Time Machine de Shikkari Shinasai',
 'Dragon Ball Z',
 'Tsubasa: Shunraiki',
 'Elf wo Karu Mono-tachi',
 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen',
 'Macross F: Close Encounter - Deculture Edition',
 'Kakumeiki Valvrave',
 'Gongitsune',
 'Top wo Nerae 2! Diebuster',
 'One Piece Movie 7: Karakuri-jou no Mecha Kyohei',
 'Bleach Movie 4: Jigoku-hen',
 'Detective Conan OVA 05: The Target is Kogoro! The Detective Boys&#039; Secret Investigation',
 'InuYasha: Kanketsu-hen',
 'Vandread: The Second Stage',
 'High School Fleet',
 'Line Offline: Salaryman',
 'Shigofumi Picture Drama',
 'Nyani ga Nyandaa Nyandaa Kamen',
 'Code Geass: Boukoku no Akito 2 - Hikisakareshi Yokuryuu',
 'Top wo Nerae! Gunbuster',
 'Detective Conan OVA 01: Conan vs. Kid vs. Yaiba',
 'Kinnikuman',
 'Peter Pan no Bouken',
 'Mashin Eiyuuden Wataru 2',
 'Detective Conan Movie 19: The Hellfire Sunflowers',
 'Yoroiden Samurai Troopers Gaiden',
 'El Hazard: The Wanderers',
 'Black★Rock Shooter',
 'Full Metal Panic!',
 'Heartcatch Precure!',
 'Mahoujin Guru Guru Movie',
 'Hakuouki OVA',
 'Shakugan no Shana Movie',
 'Fullmetal Alchemist: Brotherhood',
 'Fushigi no Umi no Nadia Specials',
 'Naruto',
 'Kaze no Stigma',
 'Detective Conan OVA 07: A Challenge from Agasa! Agasa vs. Conan and the Detective Boys',
 'Noblesse: Awakening',
 'Giniro no Kami no Agito',
 'Naruto Movie 1: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo!',
 'Jungle Taitei: Susume Leo!',
 'Omae Umasou da na',
 'Shounen Onmyouji',
 'Log Horizon',
 'Sakura Taisen',
 'Sakura Taisen: Gouka Kenran',
 'Shin Koihime†Musou: Otome Tairan',
 'Sangokushi II: Amakakeru Otoko-tachi',
 'Captain Harlock',
 'Jungle Book Shounen Mowgli',
 'Manga Sekai Mukashibanashi',
 'Nils no Fushigi na Tabi',
 'RD Sennou Chousashitsu',
 'Fullmetal Alchemist',
 'Macross Δ',
 'Dragon Ball Z Movie 06: Gekitotsu!! 100-oku Power no Senshi-tachi',
 'Pokemon Fushigi no Dungeon: Sora no Tankentai - Toki to Yami wo Meguru Saigo no Bouken',
 'One Piece Film: Gold',
 'Ginga Nagareboshi Gin',
 'Initial D Third Stage',
 'Oyayubi Hime Monogatari',
 'Shin Captain Tsubasa',
 'New Prince of Tennis OVA vs. Genius10',
 'Hakuouki Reimeiroku',
 'World Trigger',
 'Dance in the Vampire Bund',
 'Mobile Suit Gundam',
 'One Piece: Mamore! Saigo no Dai Butai',
 'Bungou Stray Dogs',
 'Mob Psycho 100',
 'Tokyo Ghoul: &quot;Pinto&quot;',
 'Mai-Otome Zwei',
 'Bounen no Xamdou',
 'D.Gray-man',
 'Mai Mai Shinko to Sennen no Mahou',

In [71]:
r1 = recommend_anime(1, 0.8)
r2 = recommend_anime(1, 0.9)
r3 = recommend_anime(1, 0.95)

In [72]:
print(len(r1))
print(len(r2))
print(len(r3))

2905
2111
1521

In [73]:
print("Threshold 0.8:", len(r1), "recommendations")
print("Threshold 0.9:", len(r2), "recommendations")
print("Threshold 0.95:", len(r3), "recommendations")

Threshold 0.8: 2905 recommendations
Threshold 0.9: 2111 recommendations
Threshold 0.95: 1521 recommendations

Performance Analysis:

When the similarity threshold increases, the number of recommendations decreases. At 0.80, the system gives 2905 recommendations, while at 0.90 it gives 2111 and at 0.95 it gives 1521. A higher threshold gives more similar recommendations but fewer results. A lower threshold gives more results but may include less similar anime.

Areas for Improvement:

The recommendation system can be improved by using more features such as anime type, number of episodes, and user ratings. Better encoding methods and more suitable similarity thresholds could also improve recommendation quality.

User-based: Finds users with similar preferences and recommends items they liked.
Item-based: Finds items that are similar to items the user already liked.

Collaborative Filtering is a recommendation technique that uses user preferences, ratings, or behavior to recommend items. It finds similar users or items and recommends items based on those similarities.