**Assignment-4**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df =pd.read_csv('/content/Patient_Data.csv')

In [3]:
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [4]:
df.shape

(6, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [7]:
select =['PatientID','Department','Doctor','BillAmount']
print(select)

['PatientID', 'Department', 'Doctor', 'BillAmount']

In [16]:
select_df =df[['PatientID','Department','Doctor','BillAmount']]
print(select_df)

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [27]:
Drop_df = df.drop(columns=['ReceptionistID','CheckInTime'])
print(Drop_df)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [28]:
BillAmount =df['BillAmount']
print(BillAmount)

0    5000.0
1       NaN
2    7500.0
3    6200.0
4       NaN
5    5000.0
Name: BillAmount, dtype: float64

In [30]:
BillAmount =df['BillAmount'].sum()
print(BillAmount)

23700.0

In [33]:
df.groupby('Department')['BillAmount'].sum()
print(df)

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2
5        101    Alice   Cardiology  Dr. Smith      5000.0               1

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45
5  2023-01-10 09:00

In [38]:
df.duplicated(subset='PatientID')

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [40]:
df = df.drop_duplicates(subset='PatientID')
print(df)

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45

In [41]:
df.shape

(5, 7)

In [42]:
BillAmount =df['BillAmount']
print(BillAmount)

0    5000.0
1       NaN
2    7500.0
3    6200.0
4       NaN
Name: BillAmount, dtype: float64

In [43]:
BillAmount =df['BillAmount'].sum()
print(BillAmount)

18700.0

In [44]:
df['BillAmount'].mean()

np.float64(6233.333333333333)

In [45]:
df['BillAmount'] = df['BillAmount'].fillna(df['BillAmount'].mean())
print(df)

   PatientID     Name   Department     Doctor   BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000               1
1        102      Bob    Neurology   Dr. John  6233.333333               2
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000               1
3        104    David   Cardiology  Dr. Smith  6200.000000               3
4        105      Eva  Dermatology   Dr. Rose  6233.333333               2

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45

/tmp/ipykernel_2209/2425535684.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BillAmount'] = df['BillAmount'].fillna(df['BillAmount'].mean())

In [57]:
billing_df=df =pd.read_csv('/content/Billing_Data.csv')

In [52]:
df.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [48]:
df.shape

(5, 3)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [83]:
Patient_df=df=pd.read_csv('/content/Patient_Data.csv')

In [84]:
merge_df =pd.merge(billing_df,Patient_df,on='PatientID')
print(merge_df)

   PatientID  InsuranceCovered  FinalAmount     Name   Department     Doctor  \
0        101              2000         3000    Alice   Cardiology  Dr. Smith
1        101              2000         3000    Alice   Cardiology  Dr. Smith
2        102              1500         3500      Bob    Neurology   Dr. John
3        103              2500         5000  Charlie  Orthopedics    Dr. Lee
4        104              3000         3200    David   Cardiology  Dr. Smith
5        105              1000         4000      Eva  Dermatology   Dr. Rose

   BillAmount  ReceptionistID       CheckInTime
0      5000.0               1  2023-01-10 09:00
1      5000.0               1  2023-01-10 09:00
2         NaN               2  2023-01-11 10:30
3      7500.0               1  2023-01-12 11:00
4      6200.0               3  2023-01-13 12:00
5         NaN               2  2023-01-14 08:45

In [85]:
Patient_df = pd.read_csv('/content/Patient_Data.csv')

Patient_df = Patient_df.drop_duplicates(subset='PatientID')

print(Patient_df)

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45

In [86]:
new_patients = pd.DataFrame({
    'PatientID':[106,107],
    'Name':['Rishi','Sneha'],
    'Department':['Cardiology','Neurology'],
    'Doctor':['Dr. Kumar','Dr. Rao'],
    'BillAmount':[4500,3500],
    'ReceptionistID':[2,1],
    'CheckInTime':['2023-01-15 10:00','2023-01-15 11:30']
})

print(new_patients)

   PatientID   Name  Department     Doctor  BillAmount  ReceptionistID  \
0        106  Rishi  Cardiology  Dr. Kumar        4500               2
1        107  Sneha   Neurology    Dr. Rao        3500               1

        CheckInTime
0  2023-01-15 10:00
1  2023-01-15 11:30

In [87]:
updated_df = pd.concat([Patient_df, new_patients], ignore_index=True)

print(updated_df)

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2
5        106    Rishi   Cardiology  Dr. Kumar      4500.0               2
6        107    Sneha    Neurology    Dr. Rao      3500.0               1

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45
5  2023-01-15 10:00
6  2023-01-15 11:30

In [88]:
billing_category = pd.DataFrame({
    'InsuranceCovered':[2000,1500,2500,3000,1000,1800,2200],
    'FinalAmount':[3000,3500,5000,3200,4000,2700,3800]
})

print(billing_category)

   InsuranceCovered  FinalAmount
0              2000         3000
1              1500         3500
2              2500         5000
3              3000         3200
4              1000         4000
5              1800         2700
6              2200         3800

In [89]:
final_df = pd.concat([updated_df, billing_category], axis=1)

print(final_df)

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2
5        106    Rishi   Cardiology  Dr. Kumar      4500.0               2
6        107    Sneha    Neurology    Dr. Rao      3500.0               1

        CheckInTime  InsuranceCovered  FinalAmount
0  2023-01-10 09:00              2000         3000
1  2023-01-11 10:30              1500         3500
2  2023-01-12 11:00              2500         5000
3  2023-01-13 12:00              3000         3200
4  2023-01-14 08:45              1000         4000
5  2023-01-15 10:00              1800         2700
6  2023-01-15 11:30              2200         3800